--영화테이블
CREATE TABLE Movie (
	movie_no	INT NOT NULL CONSTRAINT PK_MOVIE PRIMARY KEY,
	genre_no	INT NOT NULL CONSTRAINT FK_MOVIE REFERENCES GENRE(GENRE_NO),
	movie_title	varchar2(100)	NOT NULL,
	release_date	date	NOT NULL,
	running_time	number	NOT NULL,
	movie_state	int default 1 NOT NULL,
	movie_director	varchar(50)	 NOT NULL
);

--장르 테이블
CREATE TABLE Genre (
	genre_no	INT	NOT NULL CONSTRAINT PK_GENRE PRIMARY KEY,
	genre_name	varchar2(50)	NOT NULL
);
--장르 시퀀스
CREATE SEQUENCE GENRE_SEQ;
--장르 데이터 삽입
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '액션');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '코미디');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '로맨스');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '공포');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '애니메이션');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, 'SF');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '판타지');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '모험');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '범죄');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '스릴러');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '다큐멘터리');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '드라마');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '뮤지컬/공연');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '전쟁');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '가족');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '미스터리');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '사극');
INSERT INTO GENRE VALUES(GENRE_SEQ.NEXTVAL, '기타');

--회원테이블
CREATE TABLE Member (
	member_id	varchar(50)	NOT NULL CONSTRAINT PK_MEMBER PRIMARY KEY,
	member_password	varchar2(50)	NOT NULL,
	member_name	varchar2(20)	NOT NULL,
	member_birth	varchar2(30)	NOT NULL,
	member_state	int	 DEFAULT 1 NOT NULL
);
--배우 테이블
CREATE TABLE Actor (
	actor_no	INT 	NOT NULL CONSTRAINT PK_ACTOR PRIMARY KEY,
	movie_no	INT 	NOT NULL CONSTRAINT FK_ACTOR REFERENCES MOVIE(MOVIE_NO),
	actor_name	varchar2(100)	NOT NULL
);
--평점 테이블
CREATE TABLE Rate (
	rate_no	INT	NOT NULL CONSTRAINT PK_RATE PRIMARY KEY,
	member_id	VARCHAR2(50)	NOT NULL CONSTRAINT FK_RATE_MEMBER REFERENCES MEMBER(MEMBER_ID),
	movie_no	INT	NOT NULL CONSTRAINT FK_RATE_MOVIE REFERENCES MOVIE(MOVIE_NO),
	rate	number	NULL
);
--게시판 테이블
CREATE TABLE Board (
	board_no	INT NOT NULL CONSTRAINT PK_BOARD PRIMARY KEY,
	member_id	VARCHAR2(50)	NOT NULL CONSTRAINT FK_BOARD_MEMBER REFERENCES MEMBER(MEMBER_ID),
	movie_no	INT	NOT NULL CONSTRAINT FK_BOARD_MOVIE REFERENCES MOVIE(MOVIE_NO),
	board_title	varchar2(100)	NOT NULL,
	board_content	varchar2(500)	 NOT NULL,
	board_date date DEFAULT SYSDATE NOT NULL
);
--게시판 시퀀스 생성
CREATE SEQUENCE BOARD_SEQ;
--댓글 테이블
CREATE TABLE Comments (
	comments_no INT	NOT NULL CONSTRAINT PK_COMMENT PRIMARY KEY,
	board_no	INT	NOT NULL CONSTRAINT FK_COMMENT_BOARD REFERENCES BOARD(BOARD_NO),
	member_id	VARCHAR2(50)	NOT NULL CONSTRAINT FK_COMMENT_MEMBER REFERENCES MEMBER(MEMBER_ID),
	comments_content	varchar2(500) NOT NULL,
	comments_date	date	DEFAULT SYSDATE NOT NULL
);
--댓글 시퀀스 생성
CREATE SEQUENCE COMMENTS_SEQ;
--회원의 선호장르 관리 테이블
CREATE TABLE Member_Genre (
	genre_favor_no	INT	NOT NULL CONSTRAINT PK_MEMBER_GENRE PRIMARY KEY,
	genre_no 	INT	NOT NULL CONSTRAINT FK_MEMBER_GENRE_NO REFERENCES GENRE(GENRE_NO),
	member_id	varchar2(50)	NOT NULL CONSTRAINT FK_MEMBER_GENRE_ID REFERENCES MEMBER(MEMBER_ID)
);
--관련 시퀀스 생성
CREATE SEQUENCE MEMBER_GENRE_SEQ;